### PR TITLE
Made plugin "whatsthekey"

### PR DESCRIPTION
**Pull request by Perska**
Spits a message made from 8 characters. [A-Z, 0-9]
If you specify a length, it will be that long. If you use a negative instead, the characters '_' and '-' will be included.

/whatsthekey [length]

### CODE REVIEW

**Comment by Perska** [comment]
Agh, should've added a limit for the length to be only 14 characters, but whatever, not going through of this mess again.

**Comment by ShadowC-X-11** [comment]
Please add info/whatisthekey.json

**Comment by Perska** [comment]
Added.

**Comment by ShadowC-X-11** [comment]
Alright, looks good. Merging...

**Pull request merged**
